### ISSUE TITLE
Please expose type of checksums to stay compatible with Digest

### ISSUE THREAD

**Issue by madroach** [fdopen/cryptohash#1]
To be compatible with the ``Digest`` module type ``t`` needs to be exposed as ``string``. There is no need to use ``Bytes.t`` as checksum type because checksums are not supposed to be modified.

**Comment by fdopen** [comment]
it was intended as a drop-in-replacement for ocaml-sha (with a more liberal license); and ocaml-sha doesn't expose the underlying type: https://github.com/vincenthz/ocaml-sha/blob/3afdc07c696bf4ee1706700df9ecdf39e1af2dd4/sha1.mli#L24

But since it doesn't break backward compatibility, I've exposed it for you ( 7089aa6ffcef4955dce29c84b669eaf22f67978b ) . Parts of the interface are now redundant (e.g. `output`), but anyway ...

**Comment by madroach** [comment]
thanks!
